---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

trigger:
  event:
    - push

steps:
- name: build
  image: plugins/docker
  pull: always
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME##docker-}
    cache_from: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME##docker-}:${DRONE_COMMIT_BRANCH}
    dockerfile: ${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}.Dockerfile
    tags:
      - ${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:7}-${DRONE_BUILD_NUMBER}-${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}

---
kind: pipeline
name: linux-arm64

platform:
  os: linux
  arch: arm64

trigger:
  event:
    - push

steps:
- name: build
  image: plugins/docker
  pull: always
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME##docker-}
    cache_from: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME##docker-}:${DRONE_COMMIT_BRANCH}
    dockerfile: ${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}.Dockerfile
    tags:
      - ${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:7}-${DRONE_BUILD_NUMBER}-${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}

---
kind: pipeline
name: linux-arm

platform:
  os: linux
  arch: arm

trigger:
  event:
    - push

steps:
- name: build
  image: plugins/docker
  pull: always
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME##docker-}
    cache_from: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME##docker-}:${DRONE_COMMIT_BRANCH}
    dockerfile: ${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}.Dockerfile
    tags:
      - ${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:7}-${DRONE_BUILD_NUMBER}-${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}

---
kind: pipeline
name: manifest

trigger:
  event:
    - push

steps:
- name: latest
  when:
    branch:
      - stable
  image: plugins/manifest
  pull: always
  settings:
    ignore_missing: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME##docker-}:latest
    template: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME##docker-}:${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:7}-${DRONE_BUILD_NUMBER}-OS-ARCH
    platforms:
      - linux/amd64
      - linux/arm
      - linux/arm64

- name: branch
  image: plugins/manifest
  pull: always
  settings:
    ignore_missing: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME##docker-}:${DRONE_COMMIT_BRANCH}
    template: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME##docker-}:${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:7}-${DRONE_BUILD_NUMBER}-OS-ARCH
    platforms:
      - linux/amd64
      - linux/arm
      - linux/arm64

- name: branch-commit
  image: plugins/manifest
  pull: always
  settings:
    ignore_missing: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME##docker-}:${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:7}
    template: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME##docker-}:${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:7}-${DRONE_BUILD_NUMBER}-OS-ARCH
    platforms:
      - linux/amd64
      - linux/arm
      - linux/arm64

depends_on:
  - linux-amd64
  - linux-arm64
  - linux-arm

# ---
# kind: pipeline
# name: downstream

# trigger:
#   branch:
#     - master

# steps:
# - name: trigger
#   image: plugins/downstream
#   settings:
#     server: https://cloud.drone.io
#     token:
#       from_secret: drone_token
#     fork: true
#     repositories:
#       - ${DRONE_REPO_OWNER}/docker-lidarr@master
#       - ${DRONE_REPO_OWNER}/docker-radarr@master
#       - ${DRONE_REPO_OWNER}/docker-sonarr@master
#       - ${DRONE_REPO_OWNER}/docker-sonarr3@master

# depends_on:
#   - manifest
