kind: pipeline
name: default

trigger:
  event:
    exclude:
      - pull_request

steps:
- name: shellcheck
  image: koalaman/shellcheck-alpine
  pull: always
  commands:
    - shellcheck --version
    - for file in $(find ./root -type f); do echo $file; shellcheck $file; done;

- name: build
  image: plugins/docker
  pull: always
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: hotio/mono
    auto_tag: true
    cache_from: "hotio/mono"

- name: trigger  
  image: plugins/downstream
  pull: always
  settings:
    server: https://cloud.drone.io
    token:
      from_secret: drone_token
    fork: true
    repositories:
      - hotio/docker-radarr
      - hotio/docker-sonarr
      - hotio/docker-sonarr3
      - hotio/docker-lidarr
      - hotio/docker-jackett

- name: microbadger
  image: plugins/webhook
  pull: always
  settings:
    urls:
      - https://hooks.microbadger.com/images/hotio/mono/UxhndbvOkd5qMY4n615bBpP9gwo=
